[features]
seeds = false
skip-lint = false
[programs.localnet]
spl_transfer = "F1eqWRT9CUruLk9n4mX4fCYKDqSde9yLtveRaywx6vwn"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/eddy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
