[features]
seeds = false
skip-lint = false
[programs.devnet]
mpl_token_transfer = "9st7EdZS5GgDjjKVFk7gR62Smp1YtirhdNCoQax7mxJP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/eddy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
