[features]
##seeds = false
##skip-lint = false
[programs.devnet]
authority_control = "D5AxD1SpagtoL9oCdofxx7unpbvy3Zps8CFmE4F1Rrod"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/eddy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
